package duke.ui;

import duke.task.Task;

import java.util.ArrayList;

/**
 * Represents interaction messages with the user in the user interface.
 */
public class Ui {
    /**
     * Prints the welcome messages at the start of the program.
     */
    public static void printGreet() {
        String logo = " ____        _        \n"
                + "|  _ \\ _   _| | _____ \n"
                + "| | | | | | | |/ / _ \\\n"
                + "| |_| | |_| |   <  __/\n"
                + "|____/ \\__,_|_|\\_\\___|\n";
        System.out.println("Hello from\n" + logo);
        printSeparation();
        System.out.println("    Hey kid! I'm Duke *^u^*");
        System.out.println("    Seems like... you need some help? 0v0");
        printSeparation();
    }

    /**
     * Prints the exit messages at the end of the program.
     */
    public static void printBye() {
        printSeparation();
        System.out.println("    Ok cool. Hope to see you again soon... QAQ");
        printSeparation();
    }

    /**
     * Prints the existing task list.
     */
    public static void printList(ArrayList<Task> tasks) {
        printSeparation();
        if (Task.numOfTasks==0) {
            //EmptyListException
            System.out.println("    Dude, the list is empty! o_O");
        } else {
            System.out.println("    Here is the list of your tasks: ");
            for (int i = 0; i < Task.numOfTasks; i++) {
                int index = i+1;
                System.out.format("    %d.", index);
                tasks.get(i).printTask();
            }
        }
        printSeparation();
    }

    /**
     * Prints the line separation to separate user input from messages generated by the program.
     */
    public static void printSeparation() {
        System.out.println("    ____________________________________________________________");
    }

    /**
     * Prints the messages to show that task is successfully added.
     */
    public static void printTaskAddedMessage(Task t) {
        printSeparation();
        System.out.println("    " + "Got it. I've added this task: ");

        System.out.format("    ");
        t.printTask();
        ;

        System.out.format("    Now you have %d task%s in the list.%n", Task.numOfTasks,
                (Task.numOfTasks == 1) ? "" : "s");
        printSeparation();
    }

    /**
     * Prints the messages to show that the task the user referred to is invalid.
     */
    public static void printTaskNotExistMessage() {
        printSeparation();
        System.out.println("    OOPS!!! The task does not exist.");
        printSeparation();
    }

    /**
     * Prints the messages to show that the task is marked as done successfully.
     */
    public static void printMarkTaskDoneMessage() {

        System.out.println("    Nice! I've marked this task as done: ");
    }

    /**
     * Prints the messages to show that the task is successfully removed.
     */
    public static void printTaskRemovedMessage() {
        System.out.println("    Task removed successfully!");
        System.out.println("    Now you have " + Task.numOfTasks + " task" + (Task.numOfTasks>1?"s":"") + " in the list.");
    }

    /**
     * Prints the messages to show that the program is attempting to remove the task.
     */
    public static void printRemovingTaskMessage() {
        System.out.println("    Noted. I'll removed this task: ");
    }

    /**
     * Prints the list of tasks with given keyword.
     */
    public static void printFindList(ArrayList<Task> foundTasks) {
        printSeparation();
        if (foundTasks.isEmpty()) {
            System.out.println("    No task found in the list with the given keyword!");
            printSeparation();
            return;
        }

        System.out.println("    Here are the matching tasks in your list:");
        for (int i = 0; i < foundTasks.size(); i++) {
            int index = i+1;
            System.out.format("    %d.", index);
            foundTasks.get(i).printTask();
        }
        printSeparation();
    }

    /**
     * Prints the list of available user commands.
     */
    public static void printHelpMessage() {
        printSeparation();
        System.out.println("    Here's the list of available commands:");
        System.out.println("    1.help - View list of available user commands\n" +
                "    2.list - View list of tasks\n" +
                "    3.todo - Add todo\n" +
                "    4.deadline - Add deadline\n" +
                "    5.event - Add event\n" +
                "    6.delete - Delete task\n" +
                "    7.done - Mark the task as done\n" +
                "    8.find - Find tasks using keyword\n" +
                "    9.bye - Exit program");
        printSeparation();
    }
}
